language: node_js
node_js: 14.0.0

cache:
  directories:
    - node_modules

install:
  - npm install vuepress -g
  - echo "Install done!"
  
script:
  - cd docs && npm run build
  - echo "Build done!"
  
branches:
  only:
    - master
    
before_install:
  - echo "Before install"
  
addons:
  ssh_known_hosts: 18.191.12.61
 
